# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("students", "0004_auto_20150611_1523")]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="person",
            field=models.OneToOneField(
                help_text=b'Only people with the "student" flag are shown',
                on_delete=django.db.models.deletion.PROTECT,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="student_registration",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_list",
                to="classes.Section",
            ),
        ),
    ]
